info:
  app:
    name: kotlin-spring-boot-rest-jpa-jwt-starter
    version: 0.2.0-SNAPSHOT
spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
      temp:
        use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    open-in-view: true
    properties:
      hibernate.show_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true
#      hibernate.dialect.storage_engine: innodb
  datasource:
    password: Inasoft#$%
    username: inauser
    url: jdbc:postgresql://inasoft.cp5yk6b2z9qp.ap-northeast-2.rds.amazonaws.com:5432/ina_db?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: org.postgresql.Driver
    # init app_user, app_role
    initialization-mode: NEVER
    continue-on-error: true
    hikari:
      # https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration
      data-source-properties:
        cachePrepStmts: true
        useServerPrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useLocalSessionState: true
        useLocalTransactionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
      pool-name: startertest
      maximum-pool-size: 5
#  jmx:
#    default-domain: startertest
management:
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
server:
  compression:
    enabled: false
  http2:
    enabled: true
  port: 4080
  servlet:
    context-path:
  tomcat:
    accesslog:
      directory: logs
---
spring:
  profiles: test
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    # init app_user, app_role
    initialization-mode: always
    continue-on-error: true
---
user.security.jwt:
  tokenExpirationTime: 43200 # Minutes
  tokenIssuer: everyonebeauty.com
  tokenSigningKey: ${TOKEN_SIGNING_KEY:U9FdVDcRlKRV+WDzSOCmdeKkhR9MWANj1Ksti9GiXPdzgyL4LBGhFLvzDxOkJDg/JvD65s3rbcUda757Re4uAA==}

